CBL-5950: Port VS defaults from master and fix isLazy
couchbaselabs/couchbase-mobile-tools pull request #73
Opened 2024-07-02 14:05 UTC by velicuvlad

- port a3b7a758b165d96bc3985cee9081737019740f9e
- port 2dad3b185083fdda5cea1c5649130d7953257144
- fix isLazy. should be `false` not `"false"`

2024-07-02 21:57 UTC, borrrden requested changes

2024-07-02 21:57 UTC, borrrden commented on gen_defaults/cbl-defaults.json
> +                    "id": "int",
This is incorrect.  C# should be uint, so this (and C) should be removed as the default generated type is fine.

2024-07-02 21:57 UTC, borrrden commented on gen_defaults/cbl-defaults.json
> +                    "id": "int",
Same issue

2024-07-02 21:57 UTC, borrrden commented on gen_defaults/cbl-defaults.json
> +                    "id": "int",
Same issue

2024-07-03 17:16 UTC, bmeike reviewed
I defer to Jim, here

2024-07-03 17:43 UTC, velicuvlad commented
I've now also changed `euclidean` to `euclideanSquared` for the upcoming changes

2024-07-03 18:24 UTC, bmeike approved these changes

2024-07-03 22:25 UTC, merged