Enrich Command
couchbaselabs/couchbase-mobile-tools pull request #75
Opened 2024-07-11 00:40 UTC by Alexander-Baker-24

Finished writing the enrich command.

2024-07-11 01:06 UTC, borrrden requested changes
The PR also only mentions the enrich command, with no mention of the modifications to the mkindex command.

2024-07-11 01:06 UTC, borrrden commented on cblite/EnrichCommand.cc
> +        Value val = newDoc.asDict().get("data").asArray()[0].asDict().get("embedding");
Let's choose a better name than `val` as well.  `embedding` seems like a natural choice.

2024-07-11 01:06 UTC, borrrden commented on cblite/EnrichCommand.hh
> +    void enrichDocs(std::string, std::string);
I think this could probably be `const std::string&` instead

2024-07-11 01:06 UTC, borrrden commented on tests/TokenizerTest.cc
> +    //
Seems like this was a mistake?

2024-07-11 01:06 UTC, borrrden commented on vendor/couchbase-lite-core-EE
This cannot be committed, it needs to be removed

2024-07-12 00:40 UTC, borrrden requested changes

2024-07-12 00:40 UTC, borrrden commented on cblite/EnrichCommand.cc
> +                r->error() = C4Error{NetworkDomain, kC4NetErrUnknown};
Same question

2024-07-12 00:40 UTC, borrrden commented on tests/TokenizerTest.cc
> +    //
This didn't get fixed?

2024-07-12 00:40 UTC, borrrden commented on cblite/EnrichCommand.hh
> +    void enrichDocs(std::string, std::string);
Why was this conversation resolved if nothing was changed?

2024-07-12 00:40 UTC, borrrden commented on cblite/EnrichCommand.cc
> +            fail("Couldn't encode body", error);
There is no need anymore to convert to body to JSON.  This was not addressed.

2024-07-12 00:40 UTC, borrrden commented on Tool.hh
> +                if (!handled) {
This entire block is incorrectly indented

2024-07-12 17:59 UTC, Alexander-Baker-24 commented on cblite/EnrichCommand.cc
> +                r->error() = C4Error{NetworkDomain, kC4NetErrUnknown};
I believe it warns about an error. I can delete it if it is not needed.

2024-07-12 22:12 UTC, borrrden commented on cblite/EnrichCommand.cc
> +                r->error() = C4Error{NetworkDomain, kC4NetErrUnknown};
I meant the line after that.  `r->error() = C4Error{NetworkDomain, kC4NetErrUnknown};`

2024-07-15 21:44 UTC, borrrden requested changes
Just one last little thing I found

2024-07-15 21:44 UTC, borrrden commented on cblite/EnrichCommand.cc
> +        //{"--writeable", [&]{writeableFlag();}}
If this comment is not needed then remove it

2024-07-16 21:50 UTC, borrrden approved these changes

2024-07-16 21:51 UTC, merged